- src/components/Router.tsx
- 주함이가 자꾸 뭐라해서 develop 내용 일단 합쳐봅니다ㅏ.
<br />
- v6의 redirect하는 방법을 알았다!
<br />
- 왜 자꾸 나한테 머라해?
> fix: index page에서 main으로 리다이렉트될 수 있도록 추가

- src/pages/SignUp.tsx
- 회원가입 페이지 HTML 설계를 완료하였습니다.
- 유효성 검사 또한 완료하였습니다.
<br />
- 시멘틱 태그에 대해서 조금 더 잘 알수 있었습니다.
<br />
> feat: 회원가입페이지 HTML 설계

- src/pages/Login.tsx
- 로그인 페이지 html 완성
<br />
- `main` 태그는 페이지에서 의미 있는 구간을 말한다
<br />
- 다 같이 해냈다
> feat: 로그인 페이지 html 구성

- src/components/addBook/BookInfoWrapper.tsx
- src/components/addBook/BookList.tsx
- src/components/addBook/SearchBar.tsx
- CSS를 조금 더 추가하였습니다.
- 해당 브랜치에서 API 연동까지 할 예정입니다.
<br />
- 아직까지 없습니다.
<br />
- API 연동 모르겠으면 질문하겠습니다
> Feature addbook styling

- src/components/login/LoginNavSection.tsx
- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
- src/pages/Signup.tsx
- 로그인 -> 회원가입 1 -> 2 -> 3 -> 완료 애니메이션
<br />
- `<Outlet context={[handleIsAniTime]} />` ~ `useOutletContext`
<br />
- 잘했지?!
> feat: 회원가입 뷰 애니메이션 완료

- src/components/bookcase/NoCards.tsx
- src/components/bookcase/cardSection/AddBookCard.tsx
- src/components/common/MainHeader.tsx
- src/components/common/MainLayout.tsx
- src/components/login/LoginForm.tsx
- src/components/login/LoginNavSection.tsx
- src/components/main/Banner.tsx
- src/components/mypage/TopContent.tsx
- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
폰트 관련 css 제외한 모든 버튼 컴포넌트화 및 디자인 수정 내용 적용
active / inactive 기능은 오늘 머지 후 추가 예정
<br />
pathname.startsWith 메서드
<br />
> refactor: 버튼 컴포넌트화 및 디자인 수정 적용

- src/components/bookcase/NoCards.tsx
- src/components/bookcase/cardSection/AddBookCard.tsx
- src/components/common/MainHeader.tsx
- src/components/common/MainLayout.tsx
- src/components/login/LoginForm.tsx
- src/components/login/LoginNavSection.tsx
- src/components/main/Banner.tsx
- src/components/mypage/BottomContent.tsx
- src/components/mypage/TopContent.tsx
- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
“n권 읽었어요” 뷰 퍼블리싱
<br />
<br />
> Feature mypage publishing

- src/pages/Login.tsx
- 컴플릭트를 해결했습니다 :)
<br />
- 
<br />
-
> Feature common layout

- src/components/mypage/BottomContent.tsx
- src/components/mypage/TopBanner.tsx
- src/components/mypage/TopContent.tsx
- src/styles/theme.ts
마이페이지 폰트를 적용했으나, 아직 디자인팀으로부터 픽스받지 못한 폰트는 설정하지않음.
<br />
- 
<br />
> design: 마이페이지 폰트 적용 + 레이아웃 변경

- src/components/common/InputEmail.tsx
- src/components/common/InputPwd.tsx
- src/components/login/LoginForm.tsx
- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
- src/utils/auth.api.ts
- src/utils/check.ts
1. 유효성 검사
2. 중복 여부 검사
3. 비밀번호확인 기능 추가
4. Enter 입력 시 단계 넘김 추가
<br />
<br />
> 로컬 회원가입 기능 보완 및 오류 수정

- src/components/login/LoginForm.tsx
- src/pages/ToBe.tsx
- login api 붙이기하고, input 컴포넌트 리팩토링 대대적인 작업 진행 중
<br />
- 컴포넌트는 확장성을 생각하여야 한다~.~
<br />
-
> Feature login api

- src/components/login/LoginForm.tsx
- src/components/signup/ThirdStep.tsx
- etc: (로그인/회원가입) 미사용 코드 제거
<br />
- 서버가 통신이 안 돼서 error 코드가 실행되었다
<br />
-
> etc: (로그인/회원가입) 미사용 코드 제거

- src/components/bookcase/cardSection/BookCard.tsx
- src/components/common/PopUpDelete.tsx
- src/components/common/PopUpExit.tsx
- src/components/common/index.ts
- src/components/common/styled/PopUp.tsx
- src/pages/Bookcase.tsx
- src/pages/ToBe.tsx
- 모달 Wrapper 가져와서 팝업창 구현하였습니다
- (북노트 작성 및 북노트 상세페이지 뷰가 아직 구현 안 되어)
`BookCard` 에서의 삭제 토글링만 붙여놨습니다
- 삭제 API 나오면 바로 붙이도록 하겠습니다 (isbn 가져가져와서)
<br />
- 
<br />
-
> 삭제 및 나가기 확인 팝업 구현

- src/components/bookNote/DrawerWrapper.tsx
- src/components/bookNote/Navigator.tsx
- src/components/bookcase/cardSection/BookCard.tsx
- src/pages/BookNote.tsx
- src/pages/MyPage.tsx
- src/pages/Test.tsx
- 아아 드로워 들어가는 애니메이션과 드로워 뒷 배경색 지정이 안되는데 일단 랜딩 페이지 먼저 하겠습니다아아
- 누가 좀 고쳐주세여
<br />
- 
<br />
-
> Feature book note pre

- src/components/common/NavWrapper.tsx
- 아아 푸시하는거 까먹어서 여기 둡니당
- 라우터 변경된 네비게이션 반영했습니다아ㅏ 볼람볼
<br />
- 
<br />
-
> fix: navigation color 재정의 according to router url 변경

- src/components/bookNote/preNote/PreNote.tsx
- src/components/bookNote/preNote/QuestionThree.tsx
- src/pages/BookNote.tsx
- src/utils/lib/index.ts
- 독서 전단계 get & patch 완료했습니다. 아마도?
<br />
- 아아 너무 많은데 졸리니까 일단 잠
<br />
-
> Feature book note pre api

- src/components/myPage/TopContent.tsx
- 로그인, 로그아웃 버튼 클릭시 url 이동, 로그아웃 기능 넣었습니다.
<br />
- 
<br />
-
> Feature islogin kyum

- src/components/main/Banner.tsx
- src/components/myPage/BottomContent.tsx
- src/components/myPage/TopContent.tsx
- src/pages/MyPage.tsx
> Feature my page fix

- src/components/Router.tsx
- src/utils/lib/api.ts
- 랜딩페이지, 로그인, 회원가입 페이지 비로그인 상태에서 들어가면 main으로 가도록 해놨습니다
<br />
- 
<br />
- useLoginChecking 함수를 작성해봤는데 적용법을 모르겠네요ㅜ.ㅜ
> Feature randing client api

- src/components/addBook/ShowModal.tsx
- src/components/bookNote/periNote/PeriNote.tsx
- src/components/bookNote/preNote/PreNote.tsx
- src/components/myPage/TopContent.tsx
- src/pages/BookNote.tsx
- src/pages/MyPage.tsx
> Feature book note drawer

- src/components/addBook/SearchBar.tsx
- src/components/bookNote/Navigator.tsx
- src/components/bookNote/PeriNoteExample.tsx
- src/components/bookNote/periNote/PeriNote.tsx
- src/components/common/PopUpDelete.tsx
- BookNote drawer example padding 값 추가
- isqueryempty 오류 해결
<br />
- css props 에 boolean 연산문 안되나요 ..?
<br />
-
> Feature book api joam

- src/components/addBook/ShowModal.tsx
- src/components/bookNote/DrawerWrapper.tsx
- src/components/bookNote/Navigator.tsx
- src/components/bookNote/index.ts
- src/components/bookNote/periNote/PeriNote.tsx
- src/components/bookNote/preNote/PreNote.tsx
- src/components/bookcase/Navigation.tsx
- src/components/bookcase/cardSection/BookCard.tsx
- src/pages/BookNote.tsx
- src/pages/DetailBookNote.tsx
- 북노트 과정에서 생기는 버그를 수정했습니다.
<br />
- 
<br />
-
> Feature book note bug

- src/components/myPage/BottomContent.tsx
> design: n권 이미지 width 변경

- src/components/bookNote/periNote/PeriNote.tsx
- src/components/common/styled/LabelQuestion.tsx
- src/components/common/styled/LabelQuestion4Depth.tsx
- src/components/detail/ExamplePeriNote.tsx
- src/components/detail/ExamplePreNoteLabeling.tsx
- src/components/signup/ThirdStep.tsx
- src/pages/BookNote.tsx
- src/pages/Login.tsx
- 상세페이지 메인페이지 북노트 디테일
<br />
- 
<br />
-
> Feature qa joam

- src/components/bookNote/periNote/PeriNote.tsx
- src/components/bookNote/preNote/PreNote.tsx
- src/pages/BookNote.tsx
- 독서 전 중 후 state 로직 확인
- 작성 완료 전에는 질문 리스트 추가 삭제 가능하게 하기
- 4depth 버그 수정
<br />
- 
<br />
-
> Feature book note qa

- src/components/bookNote/DrawerWrapper.tsx
- src/utils/mockData.ts
> etc: 책 제목에서 2 빼기

- src/components/bookcase/Navigation.tsx
- src/pages/BookNote.tsx
- 로딩 페이지 붙이고, nav 바 수정
<br />
- `matchPath`
<br />
-
> Feature qaa joam

- src/components/bookNote/periNote/Complete.tsx
- src/components/bookNote/preNote/PreNote.tsx
> fix: complete page navigate fromUrl 변경

- src/components/addBook/BookInfoWrapper.tsx
- src/components/addBook/ShowModal.tsx
> etc: NullImage 수정

- src/components/detail/DetailArticleWrapperLabeling.tsx
- src/components/detail/ExamplePreNoteLabeling.tsx
- src/pages/BookNote.tsx
- src/pages/DetailBookNote.tsx
- 이제 진짜 안 할거임
<br />
- 
<br />
-
> 최최초최최최최최최최최종 0차 릴리즈

- src/pages/BookNote.tsx
- 기깔나는 서비스를 위한 0.001차 릴리즈
<br />
- 
<br />
-
> 이제 끝을 바라지 않기로 했다.

- .vscode/settings.json
- src/components/addBook/ShowModal.tsx
- src/components/signup/LastStep.tsx
- datetime이 string이 아닌 object로 파싱되는 문제 해결
<br />
- 
<br />
-
> fix: resolve datetime object parsing err

- src/components/bookNote/periNote/Complete.tsx
- src/components/bookNote/periNote/PeriNote.tsx
- src/components/bookNote/preNote/PreNote.tsx
- src/components/bookNote/preNote/QuestionThree.tsx
- src/components/common/index.ts
- src/components/main/RecentBooks.tsx
- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
- src/pages/BookNote.tsx
- src/pages/Bookcase.tsx
- src/pages/DetailBookNote.tsx
- src/pages/Login.tsx
- src/pages/MyPage.tsx
- book note qa 에서 브랜치 파서 진행했습니답답
- 엔터 시에 버튼 동작과 submit 동작의 중복 제거
- 유효성 검사 코드에서 setState 비동기를 고려 못한 코드가 있어서 수정했습니닫닫
<br />
- Promise  return 조작은 어려워 . .
<br />
- 회원가입 다음 단계 넘어갈 때의 탁탁 렌더링 끊기는 현상은 대체 원인이 무엇인지~.~
- 마이페이지에서 비회원일 때 "사진 선택" 까지 되도록 되어있는데, 이거 마쟈?
> Feature signup qa

- src/components/addBook/BookInfoWrapper.tsx
- src/components/addBook/ShowModal.tsx
- src/components/bookcase/cardSection/BookCard.tsx
- 저자나 옮긴이가 여러명일 경우 "000외 몇 명" 으로 수정하였습니다
<br />
- 
<br />
-
> Fix addbook and complete

- src/components/bookNote/DrawerWrapper.tsx
- src/components/bookNote/Navigator.tsx
- src/pages/BookNote.tsx
- drawer 여닫기 애니메이션 추가
https://user-images.githubusercontent.com/47105088/152965271-86d98431-98ad-4ed8-99fa-f198e1ba5da8.mp4
<br />
- state를 활용하는 `keyframe` 애니메이션과 라이브러리를 적절히 섞어 사용해야 한다는 것,
- 애니메이션 머리 아프다는 것,
<br />
- drawer 의 `border-radius` 부분 봐주실 분 봐주시면 감사합니다><
> Fix book note drawer ani

- src/components/bookcase/PeriRead.tsx
- src/components/bookcase/PostRead.tsx
- src/components/bookcase/PreRead.tsx
- src/components/bookcase/Total.tsx
- src/components/bookcase/cardSection/BookCard.tsx
- src/pages/Bookcase.tsx
- src/utils/lib/api.ts
- src/utils/lib/index.ts
현재 상태 : custom hook을 이용하여 get 완료. 하지만, 삭제는 새로고침 후 반영됨.
해야할 일 : 삭제 시, 새로고침않고도 반영
<br />
<br />
> feat: create bookcase get custom hook

- src/components/bookNote/periNote/Complete.tsx
- src/components/bookNote/stepUp/ThreeCaseModal.tsx
- src/components/bookcase/Navigation.tsx
- src/components/common/NavWrapper.tsx
1. stepup modal UI 수정
2. QA 반영
<br />
없어 임마
<br />
없어 임마
> stepup modal UI 수정 && QA 반영

- src/components/bookNote/periNote/PeriNote.tsx
- src/components/bookcase/cardSection/BookCard.tsx
- src/components/common/PopUpDelete.tsx
- src/components/landing/MobileLandingHeader.tsx
- src/components/landing/MobileLandingOne.tsx
- src/pages/DetailBookNote.tsx
- 작업 미담당 qa들 다 쳐냈습니다!
- 도움이 필요하시다면 말씀 주시길 . .
<br />
- javascript `every` 신기헷
<br />
-
> Feature qa joamm

- src/components/bookNote/periNote/Complete.tsx
design: 북노트 작성 완료 QA 반영(닫기 버튼 삭제)
<br />
<br />
없
> design: 북노트 작성 완료 QA 반영(닫기 버튼 삭제)

- src/components/addBook/ShowModal.tsx
- src/components/bookNote/periNote/PeriNote.tsx
- src/components/bookNote/preNote/PreNote.tsx
- src/components/common/PopUpDelete.tsx
- src/components/detail/ExamplePreNoteLabeling.tsx
- src/components/landing/LandingFooter.tsx
- src/components/landing/LandingOne.tsx
- src/components/login/LoginNavSection.tsx
- src/components/myPage/TopContent.tsx
- src/pages/BookNote.tsx
- src/pages/DetailBookNote.tsx
> feat: id, className 심기 for 데이터 추적

- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
- src/pages/Signup.tsx
- 회원가입에 애니메이션 `setTimeout` 관련 다 지우고, 라이브러리로 모두 바꿨어요
- `이미지 ~ 다음 버튼` 까지 애니메이션을 `렌더링` 시점으로 분리하여 애니메이션을 거러줘야 해서 Step 마다 다 나눠줬어요😥😥
- 그리하여 깜빡깜빡 거리는 현상은 완전히 없어졌을텐데, 또 다른 이슈가 생겼을지도 모르니 QA 전에 한 번 확인 부탁드리겠습니다 !!
<br />
- 
<br />
- `same key` 관련 콘솔 에러가 계속 뜨는데 아직 원인을 못찾는 중 . .~
> Feature qa joammm

- package.json
- src/pages/BookNote.tsx
- src/utils/atom.ts
- yarn.lock
`recoil-persist` 는 리코일의 내용을 로컬 스토리지에 저장해부리는 마법....
흑마법 느낌이지만 책의 정보가 오가는 우리 작은 규모의 서비스에서 필요할 수 있다고 생각한다 !
두려워 않기로...! 
**하지만 태클 환영**
> Feature qa joammmm

- src/components/bookNote/DrawerWrapper.tsx
- src/components/bookNote/ExButton.tsx
- src/components/bookNote/StepUp.tsx
- src/components/signup/FirstStep.tsx
- src/components/signup/LastStep.tsx
- src/components/signup/SecondStep.tsx
- src/components/signup/ThirdStep.tsx
- src/pages/Signup.tsx
- drawer 오타 수정
- 회원가입 완료 창에서 뒤로가기 시 메인페이지로 이동 (`ThirdStep` 에서 로그인 여부 판별하여 리디렉션)
- 회원가입 Step 별 1초 지연코드 삭제
- Step Up, 예시 Label 레이아웃 잡기 (`min-width`)
> 0321(월) PR 작업

- src/assets/icons/index.ts
- src/assets/icons/signupCheckingIcon.svg
- src/assets/icons/signupNoCheckingIcon.svg
- src/components/common/AlertLabel.tsx
- src/components/signup/FirstStep.tsx
회원가입 이용약관 동의 텍스트 추가하였습니답
[전달 및 논의 피그마](https://w1639966915-wb7331822.slack.com/archives/C02SJT6PEF3/p1649564775131619)
> Feature signup agree condition

- src/components/signup/FirstStep.tsx
- 회원가입 약관 동의에 노션 링크 첨부하였습니다
- 회원가입 버튼의 활성화 조건을 추가하였습니다
> feat: add condition notion link
